version: '3.7'
services:
  pinot:
    image: apachepinot/pinot:1.0.0
    command: "QuickStart -type batch"
    hostname: pinot
    container_name: pinot
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - pinot-advanced
  superset-pinot:
   image: apachepinot/pinot-superset:latest
   command: ""
   environment:
    SUPERSET_SECRET_KEY: "pmFmur1eluMiQDoZA+cGHhY/cA8+0+Ko7EZi5afhXWlH1oH/rQkVHNVOY1hRXAUi" 
    TALISMAN_ENABLED: "False" 
   ports:
    - "8088:8088"
   networks:
      - pinot-advanced
networks:
  pinot-advanced:
    name: pinot-advanced