services:
  pinot:
    image: apachepinot/pinot:latest
    command: "QuickStart -type batch"
    hostname: pinot
    container_name: pinot
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - pinot-labs
  kibANA-pinot:
   image: kibana/kibana:7.9.3
   command: ""
   environment:
   ports:
    - "5601:5601"
   networks:
      - pinot-labs
networks:
  pinot-advanced:
    name: pinot-labs