version: '3.7'
services:
  pinot:
    image: apachepinot/pinot:1.1.0
    command: "QuickStart -type batch"
    hostname: pinot
    container_name: pinot
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - pinot-advanced
  trino:
   image: trinodb/trino:latest
   container_name: trino
   ports:
    - "8080:8080"
   networks:
      - pinot-advanced
  looker:
    image: opstrace/looker
    container_name: looker
    ports: 
      - "9999:9999"
    networks:
      - pinot-advanced
networks:
  pinot-advanced:
    name: pinot-advanced